version: "3.1"

services:
  php:
    build: docker/php
    container_name: hr_php
    volumes:
      - "./app:/app:delegated"
    links:
      - mysql
      - memcached
    depends_on:
      - mysql
    environment:
      # xdebug: Для работы маппингов путей в PhpStorm при запуске скриптов из консоли
      # https://blog.jetbrains.com/phpstorm/2012/03/new-in-4-0-easier-debugging-of-remote-php-command-line-scripts/
      PHP_IDE_CONFIG: "serverName=dev-hr.docker"
    networks:
      - nginx-dev-proxy
  memcached:
    image: memcached:latest
    container_name: hr_memcached
  nginx:
    image: nginx:1.14
    container_name: hr_nginx
    environment:
      VIRTUAL_HOST: dev-hr.docker
    links:
      - php
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./app:/app:delegated"
    expose:
      - 80
    networks:
      nginx-dev-proxy:
        aliases:
          - dev-hr.docker
  mysql:
    image: mariadb:10.5.19
    container_name: hr_mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev_hr
      MYSQL_DATABASE: dev_hr
      MYSQL_USER: dev_hr
      MYSQL_PASSWORD: dev_hr
    volumes:
      - "./docker/mysql/data:/var/lib/mysql:delegated"
    ports:
      - "33071:3306" # Первый порт - это порт для подключения базы в PhpStorm
    networks:
      - nginx-dev-proxy

networks:
  nginx-dev-proxy:
    external: true
